Backend/tenthousand_project/app_general/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
]

Backend/tenthousand_project/app_main_content/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('maps/', views.maps, name='maps')
]

Backend/tenthousand_project/app_users/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('register', view=views.register, name='register'),
    path('list/', views.expense_list, name='expense_list'),
    path('add/', views.add_expense, name='add_expense'),
    path('delete_expense/<int:expense_id>/', views.delete_expense, name='delete_expense'),
]

Backend/tenthousand_project/tenthousand_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app_general.urls')),
    path('', include('app_main_content.urls')),
    path('users/', include('app_users.urls')),
    path("admin/", admin.site.urls),
]

Backend/tenthousand_project/app_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.date}"
    
    def get_absolute_url(self):
        return reverse('expense_list')

Backend/tenthousand_project/app_main_content/forms.py
from django import forms

class LocationForm(forms.Form):
    location = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'placeholder': 'Enter location'}))

class RadiusForm(forms.Form):
    radius = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'placeholder': 'Radius:m.'}))

Backend/tenthousand_project/app_users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Expense
from django import forms

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['amount', 'description', 'date']
        widgets = {
            'date': forms.TextInput(attrs={'type': 'text'}),
        }

Backend/tenthousand_project/app_general/views.py
from django.shortcuts import render
from django.http.response import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'app_general/Homepage.html')

Backend/tenthousand_project/app_main_content/views.py
from django.shortcuts import render, redirect
from .Maps_api import ShopFinder
from .api import api_key
from .forms import LocationForm, RadiusForm

# Create your views here.
shop_finder = ShopFinder(api_key)

global_shop_info_list = []
global_location = []

def maps(request):
    global global_shop_info_list
    global global_location
    location_form = LocationForm()
    radius_form = RadiusForm()

    if request.method == 'POST':
        location_form = LocationForm(request.POST)
        radius_form = RadiusForm(request.POST)
        sort = request.POST.get('sort')
        if location_form.is_valid():
            location = location_form.cleaned_data['location']


        if radius_form.is_valid():
            radius = radius_form.cleaned_data['radius']
            if not radius:
                radius = 4000
            try:
                if not global_shop_info_list: 
                    global_location = shop_finder.get_user_location(location) 
                    global_shop_info_list = shop_finder.get_shop_info_list(global_location, radius)
                sort_by = request.GET.get('sort_by', 'distance')
                if sort_by == 'distance':
                    if sort == 'distanceasc':
                        global_shop_info_list.sort(key=lambda x: x.get('distance', float('inf')))
                    elif sort == 'distancedsc':
                        global_shop_info_list.sort(key=lambda x: x.get('distance', float('inf')), reverse=True)
                return render(request, 'app_main_content/displaymap.html', context={'shop_result': global_shop_info_list, 'sort_by': sort_by, 'start': f'{global_location[0]},{global_location[1]}'})
            except Exception as e:
                error_message = f"An error occurred: {str(e)}"
                return render(request, 'app_main_content/map.html', context={'error_message': error_message})
    global_shop_info_list = []
    return render(request, 'app_main_content/map.html', context={'location_form': location_form, 'radius_form': radius_form})

Backend/tenthousand_project/app_users/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponseRedirect
from app_users.forms import RegisterForm
from django.contrib.auth import login
from django.urls import reverse
from .forms import ExpenseForm
from .models import Expense
from django.db.models import Sum
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request: HttpRequest):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse("home"))
    else:
        form = RegisterForm()

    context = {"form": form}
    return render(request, "app_users/register.html", context)

@login_required
def expense_list(request):
    expenses = Expense.objects.filter(user=request.user)
    total_amount = expenses.aggregate(Sum('amount'))['amount__sum'] or 0
    total_amount = 10000-total_amount
    return render(request, 'expense_list.html', {'expenses': expenses,'total_amount': total_amount})

@login_required
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.user = request.user
            expense.save()
            return redirect('expense_list')
    else:
        form = ExpenseForm()
    return render(request, 'add_expense.html', {'form': form})

@login_required
def delete_expense(request, expense_id):
    expense = Expense.objects.get(id=expense_id)
    expense.delete()
    return redirect('expense_list')

Backend/tenthousand_project/app_general/templates/app_general/Homepage.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <title>Ten Thousand Project</title>
    </head>
    <link rel="stylesheet" , href="{% static 'css/Homepage1.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Prompt">
    <script type="text/javascript" src="{% static 'js/Homepage.js' %}"></script>
    
    <body>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'maps' %}">เริ่มใช้งาน</a></li>
            {% else %}
            <li><a onclick="goto_loginpage()">เริ่มใช้งาน</a></li>
            {% endif %}
            <li><a href="#news">คุณสมบัติ</a></li>
            <li><a href="#contact">เกี่ยวกับ</a></li>
            {% if user.is_authenticated %}
            <li class="dropdown">
                <button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}</button>
                <div id="myDropdown" class="dropdown-content">
                    <a class="active" href="{% url 'expense_list' %}">Profile</a>
                    <a class="active" onclick="goto_logoutpage()">Logout</a>
                </div>
            </li>
            {% else %}
            <li style="float:right"><a class="active" onclick="goto_loginpage()">Log in</a></li>
            {% endif %}
        </ul>
          
        <div style="width: 100vw; height: 650px;background-color: #161A2A; position: relative">
            <img class ="overlay" id="image1" src="{% static 'app_general/PicHPI1.png' %}">
            <div id="header1">แผนที่ระบุตำแหน่ง<br/>ร้านค้าในรัศมี</div>
            <div id="underline1"></div>
            {% if user.is_authenticated %}
            <button onclick="goto_maps()" class="buttoncon1" >เริ่มใช้งาน</div>
            {% else %}
            <button onclick="goto_loginpage()" class="buttoncon1" >เริ่มใช้งาน</div>
            {% endif %}
            <div style="width: auto;">
                <img style="width: 100vw; z-index: 5;top: 10px; position:relative;" src="{% static 'app_general/PicwaveWG.svg' %}">
            
            <div id="contact" style="width: 100vw; height: 720px; left: 0px; top: 0px;background-color: #FAFAFF; position: relative">
                    <img id="Image2" src="{% static 'app_general/Image2.png' %}" />
                    <div id="head2">Ten Thousand Project</div>
                    <div id="text1">”นโยบาย Digital wallet 10,000 บาท ใช้จ่ายในรัศมี 4 กม. บรรเทาปัญหาปากท้องและกระตุ้นเศรษฐกิจครั้งใหญ่“ คือคำกล่าวที่ทำให้พวกเราได้เกิดข้อสงสัยขึ้น ว่าในรัศมีที่ดังกล่าวมีร้านค้าอะไรบ้าง จึงเกิดเป็นโครงงานนี้ขึ้นมา</div>
                    <div id="underline2"></div>
                    </div>
            </div>
        </div>
        <div style="width :100vw;height: 700px;margin:0px;bottom:0%;align-items: center;position: relative">
            <h2 id="news">FEATURES</h2>
            <div class="grid-container" style="position: relative ; top:-80px">
                <div class="grid-item subhead">Sign in/Sign up</div>
                <div class="grid-item subhead">ระบุตำแหน่ง</div>
                <div class="grid-item subhead">การนำทาง</div>
                <div class="grid-item subhead">ระบบโปรไฟล์</div>
                <div class="grid-item"><img src="{% static 'app_general/PicHPF1.svg' %}" alt="รูปภาพ 5"></div>
                <div class="grid-item"><img src="{% static 'app_general/PicHPF2.svg' %}" alt="รูปภาพ 6"></div>
                <div class="grid-item"><img src="{% static 'app_general/PicHPF3.svg' %}" alt="รูปภาพ 7"></div>
                <div class="grid-item"><img src="{% static 'app_general/PicHPF4.svg' %}" alt="รูปภาพ 8"></div>
                <div class="grid-item Ftext">ระบบจดจำผู้ใช้งานและเก็บไว้ในฐานข้อมูล</div>
                <div class="grid-item Ftext">การระบุตำแหน่งผู้ใช้ทั้งที่อยู่ปัจจุบันและที่กำหนดเอง</div>
                <div class="grid-item Ftext">แสดงแผ่นที่ร้านค้าพร้อมด้วยระบบนำทาง</div>
                <div class="grid-item Ftext">อัลกอริทึมที่คำนวณจำนวนเงินคงเหลือพร้อมทั้งประวัติการใช้งาน</div>
                <p><div class="vertical-line"style="left:25%"></div><div class="vertical-line"style="left:50%"></div><div class="vertical-line"style="left:75%"></div>
                </p>
            </div>
        </div>
        <div id="Nextbox"><div id="Nexttext">Copyright © 2023 Ten Thousand Project. All rights reserved.</div>

    </body>
</html>

Backend/tenthousand_project/app_main_content/templates/app_main_content/displaymap.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Ten Thousand Project</title>
    </head>
    <link rel="stylesheet" href="{% static 'css/displaymap.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Prompt">
    <script src="{% static 'js/displaymap.js' %}"></script>
    <body>
        <div style="width: 100vw;height: 100vh;">
            <div style="width: 70vw;; height: 100vh; left: 0px; top: 0px; position: absolute">
                <div id="map"></div>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkV4sjxEUVITYYDtf3qVF-E-T0aLBNfro&callback=initMap"
                async defer>
                 </script>
            </div>
            <div style="width: 30%;height: 100%;right: 0%;top: 0%;background-color: #AAAAAA;position:fixed;">
                <div style="width: 100% ;height: 12%;top: 0px;position:relative ;background-color: #ffffff;"class='container'>
                    <a href="{% url 'maps' %}">
                        <img src="{% static 'img/PicBackblack.svg' %}" style="left: 5%;position: relative;" width="auto" height="48"alt="รูปภาพ Back">
                    </a>
                        <div style="right: -18vw; height: 51%;position: relative;"><button onclick="check_value()" id="Nexttext" class="Nextbox">
                            <a href="{% url 'expense_list' %}" style="text-align: center; position: relative; top: 0.3vw;">
                                <img src="{% static 'img/PicUserblack.svg' %}" width="24" height="40"alt="รูปภาพ profile">
                            </a>
                                <B>
                                    {{ user.username }}
                                </B>
                        </div>
                    
                </div>
                <div style="width: 100% ;height: 6%;top: 5px;position:relative ;background-color: #ffffff;"class='container'>
                    <form method="post" action="{% url 'maps' %}">
                        {% csrf_token %}
                        <button type="submit" id="submit_button">
                            <img src="{% static 'img/Picsorter.svg' %}" style="margin-left: 15%;margin-right: 10%;" width="auto" height="26px"alt="รูปภาพ Sorter">
                        </button>
                        <select name="sort" id="sorttype" value={{sort}}>
                            <option value="distanceasc">lowest distance</option>
                            <option value="distancedsc">highest distance</option>
                        </select>
                    </form>
                </div>

                <div>
                    <ul class="scrollable-box" id="SLB">
                        {% if shop_result %}
                            {% for shop in shop_result %}
                                {% if shop.total %}
                                    <p>จำนวนร้านทั้งหมด : {{ shop.total }}</p>
                                {% endif %}
                            {% endfor %}
                            {% for shop in shop_result %}
                                {% if shop.name %}
                                    <li>
                                        <div class="Shopbox">
                                            <p>ชื่อร้านค้า : {{ shop.name }}</p>
                                            <p>ตำแหน่ง : {{ shop.location }}</p>
                                            <p>Rating : {{ shop.rating }}</p>
                                            <p>Rating Total : {{ shop.rating_total }}</p>
                                            <p>{{ shop.geo_locate_lat }}</p>
                                            <p>{{ shop.geo_locate_lng }}</p>
                                            <p>ระยะทาง : {{ shop.distance }} km</p> 
                                            <p>ระยะเวลาที่ใช้ในการเดินทาง (รถยนต์) : {{ shop.time }}</p>
                                            <p>{{ start }}</p>
                                            <button class="showRouteButton" data-lat="{{ shop.geo_locate_lat }}" data-lng="{{ shop.geo_locate_lng }}" data-end="{{ start }}">Navigator</button>
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

Backend/tenthousand_project/app_main_content/templates/app_main_content/map.html
{% load static %}
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                alert("Geolocation is not supported by this browser.");
            }
        }

        function showPosition(position) {
            document.getElementById("id_location").value = position.coords.latitude + "," + position.coords.longitude;
        }
    </script>
</head>
<body>
    <h1>ถ้าจะใช้ตำแหน่งปัจจุบันให้เว้นว่างไว้และถ้าจะใช้รัศมี 4 km ให้เว้นว่างไว้เหมือนกัน</h1>
    <form method="post" action="{% url 'maps' %}">
        {% csrf_token %}
        {{ location_form.as_p }}
        {{ radius_form.as_p }}
        <button type="button" onclick="getLocation()">Get Current Location</button>
        <button type="submit">Submit</button>
        <div class="label">
            <label for="sortby"><b>Sort by:</b></label>
            <select name="sort" id="sorttype" value={{sort}}>
                <option value="distanceasc">lowest distance</option>
                <option value="distancedsc">highest distance</option>
            </select>
        </div>
    </form>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    
    {% if shop_result %}
        {% for shop in shop_result %}
        <div style="background-color: gray;">
            <p>{{ shop.name }}</p>
            <p>{{ shop.location }}</p>
            <p>{{ shop.rating }}</p>
            <p>{{ shop.rating_total }}</p>
            <p>{{ shop.rating }}</p>
            <p>{{ shop.geo_locate_lat }}</p>
            <p>{{ shop.geo_locate_lng }}</p>
            <p>{{ shop.distance }} Km</p> 
            <p>{{ shop.time }}</p>
        </div>
        <p>{{ shop.total }}</p>
        {% endfor %}
    {% endif %}
</body>
</html> -->



<!DOCTYPE html>
<html>
    <head>
        <title>Ten Thousand Project</title>
    </head>
    <link rel="stylesheet" href="{% static 'css/inputpage.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Prompt">
    <script src="{% static 'js/inputpage.js' %}"></script>
    <body>
        <div style="width: 960px;; height: 1080px; left: 960px; top: 0px; position: absolute">
            <div id="map"></div>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkV4sjxEUVITYYDtf3qVF-E-T0aLBNfro&callback=initMap"
            async defer></script>
        </div>
        <form method="post" action="{% url 'maps' %}">
            {% csrf_token %}
        <div style="width: 700px; height: 150px; left: 130px; top: 344px; position: absolute; ">
            <button onclick="click_mylocation(),getLocation()" id="buttoncon1" class="buttoncon1" type="button">ตำแหน่งปัจจุบัน</button>
        </div>
        <div  style="width: 700px; height: 150px; left: 130px; top: 585px; position: absolute">

                {{ location_form.location }}

        </div>
        <div style="width: 311px; height: 103px; left: 497px; top: 837px; position: absolute">

            <button onclick="click_display()" type="submit" id="button2" class="buttoncon2" >ต่อไป</div>

        </div>
        <div style="width: 311px; height: 103px; left: 154px; top: 837px; position: absolute">      
                    {{ radius_form.radius }} 
        </div>
        </form>
            <div id="head1" >เลือกวิธีระบุตำแหน่งของคุณ</div>
            <div id="headbar">
            <div id="Bgheadbar" ></div>
            <img id="logobutton"  src="https://via.placeholder.com/80x80" />
            <a href="{% url 'home' %}"><img id="backbutton" src="{% static 'img/Back.png' %}"/></a>
            </div>
            </div>
            
    </body>
</html>

Backend/tenthousand_project/app_users/templates/add_expense.html
{% extends "template_expense.html" %}
{% load static %}
{% block li %} 
<li class="main_li"><a href="{% url 'expense_list' %}">Back</a></li>
{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/expense_add.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <h2 id="head">กรอกข้อมูล</h2>
        <form method="post" action="{% url 'add_expense' %}">
            {% csrf_token %}
            <h2>จำนวนเงิน</h2>
            {{ form.amount }}<br>
            <h2>ชื่อร้าน</h2>
            {{ form.description }}<br>
            <h2>วันที่</h2>   
            {{ form.date }}<br>
            <button type="submit">SAVE</button>
        </form>
        <script>
            flatpickr('#id_date', {
                enableTime: false,
                dateFormat: 'Y-m-d',
                defaultDate: 'today'
            });
        </script>
{% endblock %}

Backend/tenthousand_project/app_users/templates/app_users/register.html
{% extends "template_sign.html" %}

{% load static %}
{% block title %}
    Signup
{% endblock %}
{% block form %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
<form action="{% url 'register' %}" method="POST">
    <div id="HeadSignin">Sign up</div>
    <div id="SubSignin">สมัครง่ายๆ ไม่ยุ่งยาก</div>
    {% csrf_token %}
    <label class="formtext" id="Usertext" for="username"><img src="{% static 'app_users/Picusername.svg' %}" alt="รูปภาพ Username" width="24" height="24"> Username</label>
    <div class="formbox" id="Usernamebox">{{ form.username }}</div>
    
    <label class="formtext" id="Passwordtext" for="password"><img src="{% static 'app_users/Picpassword.svg' %}" alt="รูปภาพ Password" width="24" height="24"> Password</label>
    <div class="formbox" id="Passwordbox"> {{ form.password1 }}</div>

    <label class="formtext" id="Passwordtext2" for="password"><img src="{% static 'app_users/Picpassword.svg' %}" alt="รูปภาพ Password" width="24" height="24"> Re-Password</label>
    <div class="formbox" id="Passwordbox2"> {{ form.password2 }}</div>

    <label id= "Remembertext"><input type="checkbox">&nbsp;&nbsp;Term and agreement</label>
    <div id="Registertext"><a href="{% url 'login' %}"class="Textlink">Have an Account? Sign In</a></div>


    <div style="left: 10%;top: 72%;position: absolute;"><button onclick="goto_loginpage()" id="Nexttext" class="Nextbox" type="submit">NEXT</div>
    
    <!-- <div style="width: 532px; height: 100px; left: 334px; top: 773px; position: absolute">
      <button onclick="goto_loginpage()" class="buttoncon1" >NEXT</div> -->

    <!-- <div id="Nextbox"><div id="Nexttext">NEXT</div> -->

  </form>
{% endblock %}

Backend/tenthousand_project/app_users/templates/expense_list.html
{% extends "template_expense.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/expense_list.css' %}">
    <ul class="list_pro">
        {% for expense in expenses %}
            <div id="list_amount">
                {{ expense.amount|floatformat:'g' }}
            </div>
            <div id="list_description">
                {{ expense.description }} 
            </div>
            <div id="delete">
                <a href="{% url 'delete_expense' expense.id %}">Delete</a>
            </div>
        {% endfor %}
    </ul>

{% endblock %}
{% block ADD %}
    <a href="{% url 'add_expense' %}" class="ADD round">ADD</a>
{% endblock %}

Backend/tenthousand_project/app_users/templates/template_expense.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/template_expense.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Prompt">
<script type="text/javascript" src="{% static 'js/expense.js' %}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <div class="header_white">
        <p class="text_in_header">{{ total_amount|floatformat:'g' }}</p>
    </div>
    <div class="sub_header">
        <ul class="head">
            {% if user.is_authenticated %}
            <li class="main_li"><a href="{% url 'home' %}">{{ user.username }}   |</a></li>
            {% else %}
            <li class="main_li"><a href="{% url 'login' %}">{{ user.username }}   |</a></li>
            {% endif %}
            <li class="main_li"><a href="{% url 'home' %}">หน้าแรก</a></li>
            <li class="main_li"><a href="{% url 'maps' %}">กำหนดตำแหน่ง</a></li>
            <li class= "main_li" id="logout"><a href="{% url 'logout' %}">Logout</a></li>
            {% block li %} {% endblock %}
        </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% block ADD %}
    {% endblock %}
</body>

</html>

Backend/tenthousand_project/app_users/templates/template_sign.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/template.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kanit">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Prompt">


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>

    <div style="height: 100vh;width: 100vw;">
      <img id="LoginPic1" src="{% static 'app_users/PicL-Rmoney.png' %}" />
      <div id="LoginRMbox1">
        <div style="width: 598px; height: 100vh; left: 20%; top: 5%; position: absolute">
                {% block form %}
                {% endblock %}
        </div>
      </div>
    </div>
  </body>
  </html>